### ISSUE TITLE
`TypeError: this.run is not a function`

### ISSUE THREAD

**Issue by dtothefp** [jonschlinkert/templates#18] opened 2016-03-17 17:02 UTC
This issue popped up today, not sure what is happening

`"version": "0.15.11"`

```
/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/templates/lib/views.js:157
  if (view.use) this.run(view);
                     ^

TypeError: this.run is not a function
    at Views.setView (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/templates/lib/views.js:157:22)
    at DestroyableTransform._transform (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/assemble-fs/index.js:152:25)
    at DestroyableTransform.Transform._read (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:90:13)
    at DestroyableTransform.emit (events.js:182:7)
    at readableAddChunk (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:198:18)
    at DestroyableTransform.Readable.push (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:157:10)
    at DestroyableTransform.Transform.push (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at afterTransform (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:51)
    at TransformState.afterTransform (/Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:18:5
    at /Users/davidfox-powell/dev/balloon/balloon/server/static/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

**Comment by doowb** [comment] 2016-03-17 17:05
I'm looking into it.

**Comment by doowb** [comment] 2016-03-17 17:19
Fixed. @dtothefp please confirm that it's working for you. Thanks.

**Comment by jonschlinkert** [comment] 2016-03-17 20:48
closing since @dtothefp confirmed it was fixed

**Closed as completed by jonschlinkert** 2016-03-17 20:48 UTC
